using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Sitecore.Sharepoint.Data.WebServices")]
[assembly: AssemblyCompanyAttribute("Sitecore Corporation")]
[assembly: AssemblyProductAttribute("SharePoint Integration Framework 1.0.0 rev. 110617")]
[assembly: AssemblyCopyrightAttribute("© Sitecore Corporation 2011")]
[assembly: AssemblyTrademarkAttribute("Sitecore")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0 rev. 110617")]
[assembly: AssemblyFileVersionAttribute("1.0.0.3728")]

