//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Sharepoint.Data.WebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sitecore-sipwss:2650/_vti_bin/webs.asmx")]
        public string Sitecore_Sharepoint_Data_WebServices_SharepointWebs_Webs {
            get {
                return ((string)(this["Sitecore_Sharepoint_Data_WebServices_SharepointWebs_Webs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sitecore-sipwss:2650/_vti_bin/lists.asmx")]
        public string Sitecore_Sharepoint_Data_WebServices_SharepointLists_Lists {
            get {
                return ((string)(this["Sitecore_Sharepoint_Data_WebServices_SharepointLists_Lists"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sitecore-sipwss:2650/_vti_bin/sites.asmx")]
        public string Sitecore_Sharepoint_Data_WebServices_SharepointSites_Sites {
            get {
                return ((string)(this["Sitecore_Sharepoint_Data_WebServices_SharepointSites_Sites"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sitecore-sipwss:2650/_vti_bin/dws.asmx")]
        public string Sitecore_Sharepoint_Data_WebServices_sitecore_sipSharepoint_Dws {
            get {
                return ((string)(this["Sitecore_Sharepoint_Data_WebServices_sitecore_sipSharepoint_Dws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sitecore-sipwss:2650/_vti_bin/copy.asmx")]
        public string Sitecore_Sharepoint_Data_WebServices_SharepointCopy_Copy {
            get {
                return ((string)(this["Sitecore_Sharepoint_Data_WebServices_SharepointCopy_Copy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sitecore-sipwss:2650/_vti_adm/admin.asmx")]
        public string Sitecore_Sharepoint_Data_WebServices_SharepointAdmin_Admin {
            get {
                return ((string)(this["Sitecore_Sharepoint_Data_WebServices_SharepointAdmin_Admin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sitecore-sipwss/_vti_bin/sitedata.asmx")]
        public string Sitecore_Sharepoint_Data_WebServices_SharepointSiteData_SiteData {
            get {
                return ((string)(this["Sitecore_Sharepoint_Data_WebServices_SharepointSiteData_SiteData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sitecore-sipwss/_vti_bin/versions.asmx")]
        public string Sitecore_Sharepoint_Data_WebServices_SharepointVerions_Versions {
            get {
                return ((string)(this["Sitecore_Sharepoint_Data_WebServices_SharepointVerions_Versions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sitecore-sipwss/_vti_bin/views.asmx")]
        public string Sitecore_Sharepoint_Data_WebServices_SharepointViews_Views {
            get {
                return ((string)(this["Sitecore_Sharepoint_Data_WebServices_SharepointViews_Views"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sitecore-sipwss/_vti_bin/spsearch.asmx")]
        public string Sitecore_Sharepoint_Data_WebServices_SharepointSearch_QueryService {
            get {
                return ((string)(this["Sitecore_Sharepoint_Data_WebServices_SharepointSearch_QueryService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devsp1ua1/_vti_bin/search.asmx")]
        public string Sitecore_Sharepoint_Data_WebServices_SharepointMOSSSearch_QueryService {
            get {
                return ((string)(this["Sitecore_Sharepoint_Data_WebServices_SharepointMOSSSearch_QueryService"]));
            }
        }
    }
}
